spring.application.name=ai
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ai_interview}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
groq.api.key=${GROQ_API_KEY:}
groq.api.url=${GROQ_API_URL:https://api.groq.com/openai/v1/chat/completions}
groq.api.model=${GROQ_API_MODEL:llama-3.1-8b-instant}
